### PR TITLE
Japanese language support

### PR DESCRIPTION
**Pull request by Yasnen**
I have added a new language file ja.lang to support Japanese. In addition, I have implemented modifications to some of the code to make it localizable.

### CODE REVIEW

**Comment by Jagusti** [comment]
Thanks for contributing this @Yasnen ... really exciting addition. I had a few changes in progress that I've pushed to the dev branch, but that shouldn't cause any conflicts. 

Before I merge I want to take a closer look at the GM Toolbox localization, for a couple of reasons: 

1. I'm not sure about spaces in localization keys - I've avoided them so far and haven't seen any widespread use of them. I can see from running your code it doesn't break anything, but I am inclined to err on the side of caution. 
2. The original intent of Toolbox was to support any macro, not just GM Toolkit macros. I just need to handle that a bit more gracefully in the macro code, and then the localization will slot in nicely. 

I've tried some quick amends for both of these which I might either push to your fork/branch before merging, or apply post-merge. Either way, I wrote and tested them quite late, so best for me to sleep on it first and review it fresh!

**Comment by Yasnen** [comment]
I agree with you, but it would be great if you could just release the Japanese version except for GM Toolkit as soon as possible.

**Comment by Jagusti** [comment]
Could you update the PR to check the box that says "Allow edits from maintainers" please? Then I can push my updates to get this merged. Thanks 👍

**Comment by Jagusti** [comment]
Oh, I should mention that this translation string change must have happened as our commits crossed over. Maybe you can sneak it in too, it's on line 114: 
`GMTOOLKIT.Dialog.Advantage.LoseMomentum.Title" : "Lose momentum at end of Round {combatRound}"`

Previously it was 
`"GMTOOLKIT.Dialog.Advantage.LoseMomentum.Title" : "Reduce Advantage at end of Round {combatRound}", `

**Comment by Yasnen** [comment]
"Allow edits from maintainers" appears to be checked on this page. I don't know much about GitHub, so please let me know if I'm looking in the wrong place.
I have confirmed that line 114 is fine in Japanese.

Thanks for replying and reading my poor English.

**Review by Jagusti — APPROVED** [review]

**Comment by Jagusti** [comment]
Those changes are now merged into the main `dev` branch. I'll not be publishing a release for the next version (expected to be 0.9.3) yet, as there are a few other changes I want to add first, but you can certainly pull the latest version (including those improvements for handling whitespace and non-Toolkit macros) from that branch.

**Pull request merged**
